account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"

urlpatterns = [

        path('login/', views.user_login, name='login'),
        path('logout/', views.user_logout, name='logout'),
        path('', views.dashboard, name="dashboard"),
        path('password_change/', auth_views.PasswordChangeView.as_view(),
            name='password_change'),
        path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
            name='password_change_done'),
        path('password_reset/', auth_views.PasswordResetView.as_view(),
            name="password_reset"),
        path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
            name="password_reset_done"),
        path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm"),
        path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
        path('register/', views.register, name="register"),

]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
        path('', views.index, name='index'),
        path('<slug:post>/', views.content, name="content"),
        path('tag/<slug:tag_slug>/', views.postTags, name="posts_by_tag")
]

mr_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "mr_blog"
urlpatterns = [
    path('', views.redirect_to_blog),
    path('admin/', admin.site.urls),
    path('hello_world/', views.hello_world),
    path('blog/', include('blog.urls')),
    path('to_test/', views.to_test),
    path('account/', include('account.urls')),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    post_title = models.CharField(max_length = 100)
    post_slug = models.SlugField(max_length = 100)
    post_body = models.TextField()
    post_pubdate = models.DateTimeField(default = timezone.now)
    post_stat = models.CharField(choices = (
                                            ('draft', 'Draft'),
                                            ('published', 'Published'),
                                            ), default = 'published', max_length=10)
    
    tags = TaggableManager()

    def __str__(self):
        return self.post_title

class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete = models.CASCADE,
                            related_name = 'comments_post')
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'comments_user')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default = True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user} on {self.post}'

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

from .forms import LoginForm, UserRegistrationForm, UserEditForm

# Create your views here.
@login_required
def dashboard(req):
    if req.method == "POST":
        user_form = UserEditForm(instance = req.user, data = req.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance = req.user)

    return render(req, 'account/dashboard.html', {'user_form': user_form})

def register(req):
    if req.method == "POST":
        user_form = UserRegistrationForm(req.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            login(req, new_user)
            return HttpResponseRedirect(reverse('blog:index'))
    else:
        user_form = UserRegistrationForm()
    return render(req, 'account/register.html', {'user_form':user_form})

def user_login(req):
    if req.method == "POST":
        form = LoginForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(req, username = cd['username'], password = cd['password'])
            if user is not None:
                if user.is_active:
                    login(req, user)
                    return HttpResponseRedirect(reverse('blog:index'))
                else:
                    return HttpResponse("Disabled Account!")
            else:
                return HttpResponse("Invalid login!")
    else:
        form = LoginForm()
    return render(req, 'account/login.html', {'form':form})

def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('blog:index'))

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from taggit.models import Tag

from .models import Post, Comment
from .forms import CommentForm

# Create your views here.
def index(req, tag_slug=None):

    #return HttpResponse("This is the index page.")
    
    post_list = Post.objects.order_by('-post_pubdate')
    post_list = post_list.filter(post_stat="published")[:5]

    return render(req, 'blog/index.html', { 'post_list': post_list })

def postTags(req, tag_slug=None):
    post_list = Post.objects.order_by('-post_pubdate')
    post_list = post_list.filter(post_stat="published")

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    return render(req, 'blog/tag.html', { 'post_list':post_list, 'tag':tag })

def content(req, post):
    my_post = get_object_or_404(Post, post_slug=post, post_stat="published")
    
    #return HttpResponse("This is post '%s'." % my_post.post_title)

    # List of active comments for this post!
    comments = my_post.comments_post.filter(active=True)

    new_comment = None

    if req.method == "POST":
        # A comment was posted
        comment_form = CommentForm(data=req.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = my_post
            new_comment.user = req.user
            # Save the comment to the database
            new_comment.save()
    else:
            comment_form = CommentForm()

    return render(req, 'blog/content.html', { 'my_post':my_post,
                                                'comments':comments,
                                                'new_comment':new_comment,
                                                'comment_form':comment_form })

mr_blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def hello_world(req):
    return HttpResponse("Hello World!!")


def redirect_to_blog(req):
    return HttpResponseRedirect(reverse('blog:index'))


def to_test(req):
    return HttpResponse(" , ".join(dir(req)) + "<br>THIS IS TEST!!!<br><br>" + str(req.POST))

blog/templates/blog/content.html
<h1>{{ my_post.post_title }}</h1>
<h3>{{ my_post.post_pubdate }}</h3>

<p>{{ my_post.post_body }}</p>
<br>
<p class="tags">Tags:
{% for tag in my_post.tags.all %}
<a href="{% url 'blog:posts_by_tag' tag.slug %}">{{ tag.name }}</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
<hr><br>
{% with comments.count as total_comments %}
<h2>
	{{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

{% if request.user.is_authenticated %}

{% if new_comment %}
	<h2>Your comment has been added.</h2>
{% else %}
	<h2>Add a new comment</h2>
	<form method="post">
		{{ comment_form.as_p }}
		{% csrf_token %}
		<p><input type="submit" value="Add comment"></p>
	</form><br>
{% endif %}

{% else %}

	<p>For adding a new comment you need to <a href="{% url 'account:login' %}">log in</a> first.

{% endif %}

{% for comment in comments %}

<div class="comment">
	<p class="info">
	Comment {{ forloop.counter }} by {{ comment.user.first_name }}
	{{ comment.created }}
	</p>
	{{ comment.body|linebreaks }}
	<hr>
</div>
{% empty %}
<br><br>
	<p>There are no comments yet.</p><hr>
{% endfor %}

<br><br><p>All rights reserved</p>

blog/templates/blog/index.html
{% load blog_tags %}

<h1>MR Blog</h1>

{% if request.user.is_authenticated %}
<p>Welcome, {{ request.user.first_name }}<br>  <a href="{% url 'account:dashboard' %}">Dashboard</a>  <a href="{% url 'account:logout' %}">Logout</a></p>
{% endif %}
<br>
<p>This is my blog, I've written {% total_posts %} posts so far.</p>
{% if post_list %}
	<ul>
		{% for post in post_list %}
		<li><a href="{% url 'blog:content' post.post_slug %}"><h2>{{ post.post_title }}</h2></a></li>
		<p>{{ post.post_body }}</p>
		<br>
		<h3>{{ post.post_pubdate }}</h3>
		<br><br>
		{% endfor %}
	</ul>
{% else %}
<p>No posts are available!</p>
{% endif %}

blog/templates/blog/tag.html
<h1>MR Blog</h1>
<br>

{% if post_list %}
	<ul>
		{% for post in post_list %}
		<li><a href="{% url 'blog:content' post.post_slug %}"><h2>{{ post.post_title }}</h2></a></li>
		<p>{{ post.post_body }}</p>
		<br>
		<h3>{{ post.post_pubdate }}</h3>
		<br><br>
		{% endfor %}
	</ul>
{% else %}
<p>No posts are available!</p>
{% endif %}